apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nop-paaf
  name: nop-paaf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nop-paaf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nop-paaf
    spec:
      containers:
      - image: luebken/nop-paaf
        name: nop-paaf
        ports:
        - containerPort: 8081